# Generated by Django 3.2.15 on 2022-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('BLOCKED', 'blocked')], default='ACTIVE', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(blank=True, default='Fullname', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('BLOCKED', 'blocked')], default='ACTIVE', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('discount_id', models.IntegerField(blank=True, null=True)),
                ('discount_value', models.FloatField()),
                ('creator_id', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('COMPLETED', 'completed'), ('DELETED', 'deleted')], default='ACTIVE', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('DELETED', 'deleted')], default='ACTIVE', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('price_current', models.FloatField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('BLOCKED', 'blocked')], default='ACTIVE', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
